<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Proxify.Common\Proxify.Common.csproj" />
    <ProjectReference Include="..\Proxify.Client\Proxify.Client.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Proxy.SelfTest</RootNamespace>
  </PropertyGroup>

</Project>
