<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Proxify.Client.Gui</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Proxify.Common\Proxify.Common.csproj" />
    <ProjectReference Include="..\Proxify.Client\Proxify.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.3.22" />
    <PackageReference Include="Avalonia.Desktop" Version="11.3.22" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.22" />
  </ItemGroup>

</Project>